# Generated by Django 3.1.3 on 2020-12-02 02:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=255, null=True)),
                ('position_title', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('link_profile1', models.URLField(blank=True, null=True)),
                ('link_profile2', models.URLField(blank=True, null=True)),
                ('link_profile3', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Realtor Detail Page',
                'verbose_name_plural': 'Realtor Detail Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RealtorListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Realtor Listing Page',
                'verbose_name_plural': 'Realtor Listing Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RealtorProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project_page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_realtor', to='project.projectdetailpage')),
                ('realtor_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_project', to='realtor.realtordetailpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
