# Generated by Django 3.1.3 on 2020-12-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloglistingpage_title_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='blog_detail_pages',
            field=models.ManyToManyField(blank=True, related_name='category_blog_detail', to='blog.BlogDetailPage'),
        ),
    ]
