# Generated by Django 3.1.3 on 2020-12-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_blog_detail_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='blog_detail_pages',
            new_name='category_blog_detail',
        ),
    ]
