# Generated by Django 3.1.3 on 2020-12-04 02:08

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201204_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='category_blog_detail',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='category_blog_detail', to='blog.BlogDetailPage'),
        ),
    ]
